In [3]:
import numpy as np

# 랜덤시드 고정시키기
np.random.seed(3)

from keras.preprocessing.image import ImageDataGenerator

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'hard_handwriting_shape/test',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

# 모델 구성하기
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 모델 엮기
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator,
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print("-- Predict --")

output = model.predict_generator(
            test_generator,
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)

# 결과 (원래는 40% 수준)
# -- Evaluate --
# accuracy: 40.00%


Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.
Epoch 1/200


C:\Users\TJ\AppData\Local\Temp\ipykernel_3000\871639182.py:46: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(


15/15 [==============================] - 4s 66ms/step - loss: 1.0120 - accuracy: 0.6444 - val_loss: 1.2747 - val_accuracy: 0.3333
Epoch 2/200
15/15 [==============================] - 1s 35ms/step - loss: 0.2151 - accuracy: 1.0000 - val_loss: 2.3866 - val_accuracy: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 31ms/step - loss: 0.0310 - accuracy: 1.0000 - val_loss: 3.8818 - val_accuracy: 0.3333
Epoch 4/200
15/15 [==============================] - 0s 31ms/step - loss: 0.0028 - accuracy: 1.0000 - val_loss: 4.7924 - val_accuracy: 0.3333
Epoch 5/200
15/15 [==============================] - 1s 32ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 5.1745 - val_accuracy: 0.3333
Epoch 6/200
15/15 [==============================] - 1s 32ms/step - loss: 6.4536e-04 - accuracy: 1.0000 - val_loss: 5.2561 - val_accuracy: 0.3333
Epoch 7/200
15/15 [==============================] - 1s 34ms/step - loss: 5.0399e-04 - accuracy: 1.0000 - val_loss: 5.3220 - val_accuracy: 0.3333
Epoch 8/20

15/15 [==============================] - 1s 35ms/step - loss: 1.2318e-06 - accuracy: 1.0000 - val_loss: 8.7025 - val_accuracy: 0.3333
Epoch 58/200
15/15 [==============================] - 1s 33ms/step - loss: 1.1947e-06 - accuracy: 1.0000 - val_loss: 8.7283 - val_accuracy: 0.3333
Epoch 59/200
15/15 [==============================] - 1s 33ms/step - loss: 1.1259e-06 - accuracy: 1.0000 - val_loss: 8.7544 - val_accuracy: 0.3333
Epoch 60/200
15/15 [==============================] - 1s 34ms/step - loss: 1.0941e-06 - accuracy: 1.0000 - val_loss: 8.7822 - val_accuracy: 0.3333
Epoch 61/200
15/15 [==============================] - 1s 34ms/step - loss: 1.0490e-06 - accuracy: 1.0000 - val_loss: 8.8058 - val_accuracy: 0.3333
Epoch 62/200
15/15 [==============================] - 1s 36ms/step - loss: 1.0120e-06 - accuracy: 1.0000 - val_loss: 8.8307 - val_accuracy: 0.3333
Epoch 63/200
15/15 [==============================] - 1s 34ms/step - loss: 9.7486e-07 - accuracy: 1.0000 - val_loss: 8.8552 - val_a

Epoch 113/200
15/15 [==============================] - 1s 36ms/step - loss: 2.4637e-07 - accuracy: 1.0000 - val_loss: 9.6990 - val_accuracy: 0.3333
Epoch 114/200
15/15 [==============================] - 1s 37ms/step - loss: 2.4107e-07 - accuracy: 1.0000 - val_loss: 9.7145 - val_accuracy: 0.3333
Epoch 115/200
15/15 [==============================] - 1s 36ms/step - loss: 2.3842e-07 - accuracy: 1.0000 - val_loss: 9.7276 - val_accuracy: 0.3333
Epoch 116/200
15/15 [==============================] - 1s 36ms/step - loss: 2.3047e-07 - accuracy: 1.0000 - val_loss: 9.7400 - val_accuracy: 0.3333
Epoch 117/200
15/15 [==============================] - 1s 36ms/step - loss: 2.2517e-07 - accuracy: 1.0000 - val_loss: 9.7536 - val_accuracy: 0.3333
Epoch 118/200
15/15 [==============================] - 1s 36ms/step - loss: 2.2252e-07 - accuracy: 1.0000 - val_loss: 9.7643 - val_accuracy: 0.3333
Epoch 119/200
15/15 [==============================] - 1s 36ms/step - loss: 2.1987e-07 - accuracy: 1.0000 - val_

15/15 [==============================] - 0s 22ms/step - loss: 9.5367e-08 - accuracy: 1.0000 - val_loss: 10.3184 - val_accuracy: 0.3333
Epoch 169/200
15/15 [==============================] - 0s 23ms/step - loss: 9.2718e-08 - accuracy: 1.0000 - val_loss: 10.3299 - val_accuracy: 0.3333
Epoch 170/200
15/15 [==============================] - 0s 18ms/step - loss: 9.2718e-08 - accuracy: 1.0000 - val_loss: 10.3402 - val_accuracy: 0.3333
Epoch 171/200
15/15 [==============================] - 0s 18ms/step - loss: 9.2718e-08 - accuracy: 1.0000 - val_loss: 10.3490 - val_accuracy: 0.3333
Epoch 172/200
15/15 [==============================] - 0s 18ms/step - loss: 9.0069e-08 - accuracy: 1.0000 - val_loss: 10.3566 - val_accuracy: 0.3333
Epoch 173/200
15/15 [==============================] - 0s 19ms/step - loss: 9.0069e-08 - accuracy: 1.0000 - val_loss: 10.3675 - val_accuracy: 0.3333
Epoch 174/200
15/15 [==============================] - 0s 19ms/step - loss: 8.7420e-08 - accuracy: 1.0000 - val_loss: 10

C:\Users\TJ\AppData\Local\Temp\ipykernel_3000\871639182.py:56: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  scores = model.evaluate_generator(
C:\Users\TJ\AppData\Local\Temp\ipykernel_3000\871639182.py:65: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  output = model.predict_generator(


[[0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.031 0.000 0.969]
 [0.220 0.001 0.779]
 [0.263 0.004 0.733]]
